name: zenith_zero
description: "Zenith Zero: Idle Descent — auto-RPG dungeon descender."
publish_to: 'none'
version: 1.2.0+4

environment:
  sdk: ^3.11.5

dependencies:
  flame: ^1.37.0
  flame_audio: ^2.12.1
  flutter:
    sdk: flutter
  provider: ^6.1.5
  shared_preferences: ^2.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.5

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "/Users/twang/Downloads/images/idle-tower-def-pixel-style-game-mobile-app-icon--n.png"
  min_sdk_android: 21

flutter_native_splash:
  color: "#000000"
  image: "/Users/twang/Downloads/images/idle-tower-def-pixel-style-game-mobile-app-icon--n.png"
  android: true
  ios: true
  fullscreen: true

flutter:
  uses-material-design: true
  assets:
    - assets/audio/
